# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET http://localhost:5095/api/Blog

### 
POST http://localhost:5095/api/Blog
Content-Type: application/json
{
  "title": "My New Blog Post",
  "description": "This is my blog post.",
  "imagePath": "/images/post.jpg",
  "userId": 1,
  "tagIds": [1, 3]
}
###
PUT http://localhost:5095/api/Blog/1
Content-Type: application/json
{
  "title": "My New Blog Post (edited)",
  "description": "This is my blog post.",
  "imagePath": "/images/post.jpg",
  "userId": 1,
  "tagIds": [2, 3]
}
###
DELETE http://localhost:5095/api/Blog/3
###
POST http://localhost:5095/api/auth/login
Content-Type: application/json
###
POST http://localhost:5095/api/auth/signup
Content-Type: application/json
{
    "FullName": "HamzaBeta",
  "Email": "hamza@test2.com",
  "HashedPassword":"12345678Ha#$"
}